---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pgdump
    tag: "1.1"

inputs:
  - name: pipeline-scripts
outputs:
  - name: service-instance-usage

run:
  path: sh
  args:
  - -exc
  - |
    node pipeline-scripts/scripts/backup-database.js
